### PR TITLE
Test for table functions

### PR DESCRIPTION
**Pull request by Jacobb164**
Made tests for the table generation functions using dummy data. 

David please check new test outputs which are found CARS-2\carsurvey2\tests\testthat. There are 11 new tests for table outputs. Build and reinstall carssurvey2 package before tests for dummy data. Thanks

### CODE REVIEW

**Review by foster999 — CHANGES_REQUESTED** [review]
Hi @Jacobb164, sorry it's taken me a while to get round to this. At first glance all looks good, but I'd like to give the tests a run. I can't currently build the package from this branch, but @shilohd has made changes on master to fix this. Please could you rebase this branch?

As an aside, I discovered a useful function for installing a packages dependencies before building - `devtools::install_deps("carsurvey2")`

**Review by foster999 — COMMENTED** [review]
I deleted success cat to get these running on the current branch and am assuming that @shilohd's refactor doesn't affect the functionality tested here.

NB: I can be very straight when giving feedback 🗡️ Your code has been written to a great standard, and comments here are just suggestions for improvements. I'd discuss these with @shilohd, to decide if you want to take any of them on.

# General comments

## Input data

All tests use dummy data that has been run through `data_rename_cols`. Where this and other functions are used to generate test input data, it creates additional factors that can affect whether a test passes or not. As such, these act more like integration tests - they assert that a function works, given the output of other functions. It's worth considering if these warrant unit level test to assure them independently of other functions.

To make these more unit-based test, you could directly specify input data, rather than using other functions to manipulate the default dummy dataset. These input datasets should be very minimal and look to test only the required functionality.

I would suggest that the complex dummy data from `carsurvey2::dummy_data` is only used for integration and end-to-end testing. While simple, tailored example data should be used for unit tests.

## Expected outcomes

There's always a temptation to run test examples and hardcode the output values as the expected output. I suspect that this approach has been taken here. If possible, expected outputs should instead be calculated using a different means (not by running the code that is to be tested).

Using the example `test_that("Function checks percentages of factors", ...`, I would expect the input to be a very simple dataframe with 4 or so records. This would allow you to assert simple output proportions like 0, 0.25 and 1.

To compare these suggestions to the existing tests- I can't currently see what input data is being used in the tests and I can't easily verify output proportions like `0.1672515`.

# Testing success

All tests added by the PR pass. 🎉 

I noticed that tests for `derive_code_status` fail. This function is used in a number of tests here to generate input data, so I'd recommend that these tests are fixed before relying on the function.

Tests for `calc_multi_col_freqs` also fail, but this function is not used in the tests added by this PR.

**Comment by shilohd** [comment]
Please pull before making any more changes - I updated the calc_freq_operations function. You might have to change the test slightly. 

calc_freq_operations currently fails the unit test - this is good news as it shows that your unit test was really helpful! The function only works with a specific number of input columns. Please change the way column [[1]] is recoded in line with other frequency calculation functions (using dplyr recode).

**Comment by Jacobb164** [comment]
> Please pull before making any more changes - I updated the calc_freq_operations function. You might have to change the test slightly.
> 
> calc_freq_operations currently fails the unit test - this is good news as it shows that your unit test was really helpful! The function only works with a specific number of input columns. Please change the way column [[1]] is recoded in line with other frequency calculation functions (using dplyr recode).

**Comment by Jacobb164** [comment]
@shilohd I have updated the calc_freq_operations function and test as advised. Could you please check test again.

**Pull request merged**
